services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=tourplanner
      - POSTGRES_USER=tourplanner
      - TZ=UTC
      - PGTZ=UTC
  tourplanner:
    image: if23b126/tourplannerbe:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/postgres"